# Generated by Django 5.2.2 on 2025-06-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=150)),
                ('spesialisasi', models.CharField(choices=[('uiux', 'UI/UX'), ('frontend', 'Front End'), ('backend', 'Back End'), ('fullstack', 'Full Stack'), ('dataanalyst', 'Data Analyst'), ('cybersecurity', 'Cyber Security')], max_length=50)),
                ('max_bimbingan', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Dosen',
            },
        ),
        migrations.CreateModel(
            name='JadwalBimbingan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(choices=[('senin', 'Senin'), ('selasa', 'Selasa'), ('rabu', 'Rabu'), ('kamis', 'Kamis'), ('jumat', 'Jumat'), ('sabtu', 'Sabtu'), ('minggu', 'Minggu')], max_length=10)),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('kuota', models.PositiveIntegerField(default=1)),
                ('ruangan', models.CharField(blank=True, max_length=100)),
                ('keterangan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('tersedia', 'Tersedia'), ('terisi', 'Terisi'), ('tidak_aktif', 'Tidak Aktif')], default='tersedia', max_length=15)),
                ('is_recurring', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jadwal Bimbingan',
                'verbose_name_plural': 'Jadwal Bimbingan',
                'ordering': ['hari', 'jam_mulai'],
            },
        ),
        migrations.CreateModel(
            name='PendaftaranBimbingan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_bimbingan', models.DateField()),
                ('topik', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Menunggu Konfirmasi'), ('approved', 'Disetujui'), ('rejected', 'Ditolak'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], default='pending', max_length=15)),
                ('catatan_dosen', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pendaftaran Bimbingan',
                'verbose_name_plural': 'Pendaftaran Bimbingan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PengajuanJudul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('tanggal_pengajuan', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='pending', max_length=20)),
                ('catatan', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spesialisasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('deskripsi', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Spesialisasi',
            },
        ),
    ]
