# Generated by Django 5.2.2 on 2025-06-15 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dosen', '0001_initial'),
        ('mahasiswa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jadwalbimbingan',
            name='dosen',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Dosen'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pendaftaranbimbingan',
            name='jadwal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dosen.jadwalbimbingan'),
        ),
        migrations.AddField(
            model_name='pendaftaranbimbingan',
            name='mahasiswa',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Mahasiswa'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pengajuanjudul',
            name='mahasiswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosen_pengajuan_judul', to='mahasiswa.mahasiswa'),
        ),
        migrations.AlterUniqueTogether(
            name='pendaftaranbimbingan',
            unique_together={('jadwal', 'mahasiswa', 'tanggal_bimbingan')},
        ),
    ]
