# Generated by Django 5.2.2 on 2025-06-22 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jadwalbimbingan',
            options={},
        ),
        migrations.RemoveField(
            model_name='jadwalbimbingan',
            name='updated_at',
        ),
    ]
