# Generated by Django 5.2.2 on 2025-06-15 13:57

import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryPengajuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_lama', models.CharField(max_length=20)),
                ('status_baru', models.CharField(max_length=20)),
                ('keterangan', models.TextField(blank=True, default='')),
                ('tanggal_perubahan', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-tanggal_perubahan'],
            },
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('jurusan', models.CharField(max_length=100)),
                ('angkatan', models.IntegerField()),
                ('ipk', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('sks_lulus', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Mahasiswa',
            },
        ),
        migrations.CreateModel(
            name='NilaiTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_pembimbing', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('nilai_penguji1', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('nilai_penguji2', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('nilai_akhir', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('keterangan', models.TextField(blank=True, default='')),
                ('tanggal_sidang', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Nilai TA',
            },
        ),
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(default='', max_length=100)),
                ('pesan', models.TextField(default='')),
                ('tipe', models.CharField(choices=[('success', 'Sukses'), ('warning', 'Peringatan'), ('info', 'Info')], default='info', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PengajuanJudul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(blank=True, default='', max_length=150, verbose_name='Judul Penelitian')),
                ('judul_inggris', models.CharField(blank=True, default='', max_length=150, verbose_name='Judul dalam Bahasa Inggris')),
                ('deskripsi', models.TextField(blank=True, default='', help_text='Berikan deskripsi singkat tentang penelitian yang akan dilakukan', verbose_name='Deskripsi Singkat')),
                ('bidang_penelitian', models.CharField(choices=[('artificial_intelligence', 'Artificial Intelligence'), ('machine_learning', 'Machine Learning'), ('web_development', 'Web Development'), ('mobile_development', 'Mobile Development'), ('data_science', 'Data Science'), ('cybersecurity', 'Cybersecurity'), ('network', 'Network & Infrastructure'), ('game_development', 'Game Development'), ('iot', 'Internet of Things (IoT)'), ('blockchain', 'Blockchain'), ('computer_vision', 'Computer Vision'), ('nlp', 'Natural Language Processing'), ('other', 'Lainnya')], default='other', max_length=50, verbose_name='Bidang Penelitian')),
                ('metodologi', models.CharField(choices=[('quantitative', 'Kuantitatif'), ('qualitative', 'Kualitatif'), ('mixed', 'Mixed Method'), ('experimental', 'Eksperimental'), ('case_study', 'Studi Kasus'), ('design_research', 'Design Research'), ('action_research', 'Action Research')], default='case_study', max_length=50, verbose_name='Metodologi Penelitian')),
                ('teknologi', models.TextField(blank=True, default='', help_text='Sebutkan teknologi, tools, atau framework yang akan digunakan', verbose_name='Teknologi yang Digunakan')),
                ('latar_belakang', models.TextField(blank=True, default='', help_text='Jelaskan latar belakang masalah yang akan diteliti', verbose_name='Latar Belakang')),
                ('tujuan', models.TextField(blank=True, default='', help_text='Sebutkan tujuan yang ingin dicapai dari penelitian ini', verbose_name='Tujuan Penelitian')),
                ('manfaat', models.TextField(blank=True, default='', help_text='Jelaskan manfaat yang diharapkan dari penelitian ini', verbose_name='Manfaat Penelitian')),
                ('waktu_mulai', models.DateField(default=datetime.date.today, verbose_name='Waktu Mulai Penelitian')),
                ('waktu_selesai', models.DateField(blank=True, help_text='Kosongkan jika belum ditentukan (default: 6 bulan dari tanggal mulai)', null=True, verbose_name='Target Waktu Selesai')),
                ('rencana_kerja', models.TextField(blank=True, default='', help_text='Outline rencana kerja atau timeline penelitian', verbose_name='Rencana Kerja')),
                ('catatan', models.TextField(blank=True, default='', verbose_name='Catatan Tambahan')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Review'), ('reviewed', 'Sedang Direview'), ('approved', 'Disetujui'), ('rejected', 'Ditolak'), ('revision', 'Perlu Revisi')], default='pending', max_length=20)),
                ('tanggal_pengajuan', models.DateTimeField(default=django.utils.timezone.now)),
                ('tanggal_review', models.DateTimeField(blank=True, null=True)),
                ('tanggal_keputusan', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pengajuan Judul Tugas Akhir',
                'verbose_name_plural': 'Pengajuan Judul Tugas Akhir',
                'ordering': ['-tanggal_pengajuan'],
            },
        ),
        migrations.CreateModel(
            name='PengajuanTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidang_minat', models.CharField(choices=[('web_development', 'Web Development'), ('mobile_development', 'Mobile Development'), ('data_science', 'Data Science & Analytics'), ('artificial_intelligence', 'Artificial Intelligence'), ('cyber_security', 'Cyber Security'), ('game_development', 'Game Development'), ('network_systems', 'Network & Systems'), ('other', 'Lainnya')], default='other', max_length=50, verbose_name='Bidang Minat')),
                ('keterangan', models.TextField(blank=True, default='', help_text='Jelaskan alasan dan rencana penelitian Anda (minimal 50 karakter)', verbose_name='Keterangan')),
                ('semester', models.CharField(choices=[('7', 'Semester 7'), ('8', 'Semester 8'), ('9', 'Semester 9'), ('10', 'Semester 10+')], default='7', max_length=2, verbose_name='Semester Pengajuan')),
                ('ipk', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)], verbose_name='IPK Saat Ini')),
                ('sks_lulus', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Jumlah SKS yang Telah Lulus')),
                ('persetujuan', models.BooleanField(default=False, verbose_name='Persetujuan Data')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Persetujuan'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='pending', max_length=20, verbose_name='Status Pengajuan')),
                ('tanggal_pengajuan', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tanggal Pengajuan')),
                ('tanggal_diperbarui', models.DateTimeField(auto_now=True, verbose_name='Tanggal Diperbarui')),
                ('catatan_admin', models.TextField(blank=True, default='', help_text='Catatan dari admin mengenai pengajuan ini', verbose_name='Catatan Admin')),
            ],
            options={
                'verbose_name': 'Pengajuan Tugas Akhir',
                'verbose_name_plural': 'Pengajuan Tugas Akhir',
                'ordering': ['-tanggal_pengajuan'],
            },
        ),
    ]
