# Generated by Django 5.2.2 on 2025-06-15 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dosen', '0002_initial'),
        ('mahasiswa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historypengajuan',
            name='diubah_oleh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='dosen_pembimbing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dosen.dosen'),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nilaita',
            name='dosen_penguji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dosen.dosen'),
        ),
        migrations.AddField(
            model_name='nilaita',
            name='mahasiswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mahasiswa.mahasiswa'),
        ),
        migrations.AddField(
            model_name='notifikasi',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahasiswa_notifikasi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pengajuanjudul',
            name='dosen_pembimbing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dosen.dosen'),
        ),
        migrations.AddField(
            model_name='pengajuanjudul',
            name='mahasiswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mahasiswa.mahasiswa'),
        ),
        migrations.AddField(
            model_name='historypengajuan',
            name='pengajuan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='mahasiswa.pengajuanjudul'),
        ),
        migrations.AddField(
            model_name='pengajuanta',
            name='mahasiswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan_ta', to=settings.AUTH_USER_MODEL, verbose_name='Mahasiswa'),
        ),
    ]
