# Generated by Django 5.2.2 on 2025-06-16 00:15

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengajuanjudul',
            name='bidang_penelitian',
            field=models.CharField(choices=[('artificial_intelligence', 'Artificial Intelligence'), ('machine_learning', 'Machine Learning'), ('web_development', 'Web Development'), ('mobile_development', 'Mobile Development'), ('data_science', 'Data Science'), ('cybersecurity', 'Cybersecurity'), ('network', 'Network & Infrastructure'), ('game_development', 'Game Development'), ('iot', 'Internet of Things (IoT)'), ('blockchain', 'Blockchain'), ('computer_vision', 'Computer Vision'), ('nlp', 'Natural Language Processing'), ('other', 'Lainnya')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='pengajuanjudul',
            name='catatan',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pengajuanjudul',
            name='deskripsi',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pengajuanjudul',
            name='judul',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='pengajuanjudul',
            name='judul_inggris',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='pengajuanjudul',
            name='latar_belakang',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pengajuanjudul',
            name='manfaat',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pengajuanjudul',
            name='metodologi',
            field=models.CharField(choices=[('quantitative', 'Kuantitatif'), ('qualitative', 'Kualitatif'), ('mixed', 'Mixed Method'), ('experimental', 'Eksperimental'), ('case_study', 'Studi Kasus'), ('design_research', 'Design Research'), ('action_research', 'Action Research')], default='case_study', max_length=50),
        ),
        migrations.AlterField(
            model_name='pengajuanjudul',
            name='rencana_kerja',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pengajuanjudul',
            name='teknologi',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pengajuanjudul',
            name='tujuan',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pengajuanjudul',
            name='waktu_mulai',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='pengajuanjudul',
            name='waktu_selesai',
            field=models.DateField(blank=True, help_text='Kosongkan jika belum ditentukan', null=True),
        ),
        migrations.AlterField(
            model_name='pengajuanta',
            name='bidang_minat',
            field=models.CharField(choices=[('web_development', 'Web Development'), ('mobile_development', 'Mobile Development'), ('data_science', 'Data Science & Analytics'), ('artificial_intelligence', 'Artificial Intelligence'), ('cyber_security', 'Cyber Security'), ('game_development', 'Game Development'), ('network_systems', 'Network & Systems'), ('other', 'Lainnya')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='pengajuanta',
            name='catatan_admin',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pengajuanta',
            name='ipk',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)]),
        ),
        migrations.AlterField(
            model_name='pengajuanta',
            name='keterangan',
            field=models.TextField(blank=True, default='', help_text='Minimal 50 karakter'),
        ),
        migrations.AlterField(
            model_name='pengajuanta',
            name='mahasiswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan_ta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pengajuanta',
            name='persetujuan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pengajuanta',
            name='semester',
            field=models.CharField(choices=[('7', 'Semester 7'), ('8', 'Semester 8'), ('9', 'Semester 9'), ('10', 'Semester 10+')], default='7', max_length=2),
        ),
        migrations.AlterField(
            model_name='pengajuanta',
            name='sks_lulus',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pengajuanta',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu Persetujuan'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='pengajuanta',
            name='tanggal_diperbarui',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pengajuanta',
            name='tanggal_pengajuan',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
