# Generated by Django 5.2.2 on 2025-06-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=20, unique=True, verbose_name='NIP')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Lengkap')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('spesialisasi', models.CharField(max_length=100, verbose_name='Spesialisasi')),
            ],
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=20, unique=True, verbose_name='NIM')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Lengkap')),
                ('jurusan', models.CharField(max_length=100, verbose_name='Jurusan')),
                ('angkatan', models.IntegerField(verbose_name='Angkatan')),
                ('ipk', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='IPK')),
                ('sks_lulus', models.IntegerField(verbose_name='SKS Lulus')),
                ('dosen_pembimbing', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dosen Pembimbing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Data Mahasiswa',
                'ordering': ['nim'],
            },
        ),
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('pesan', models.TextField()),
                ('tipe', models.CharField(choices=[('success', 'Sukses'), ('warning', 'Peringatan'), ('info', 'Info')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PengajuanTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('tanggal_pengajuan', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='pending', max_length=20)),
                ('catatan', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyaratTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_ipk', models.DecimalField(decimal_places=2, default=2.5, max_digits=3)),
                ('min_sks', models.IntegerField(default=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Syarat TA',
            },
        ),
    ]
