# Generated by Django 5.2.2 on 2025-06-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminkampus', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengajuanta',
            name='catatan',
        ),
        migrations.RemoveField(
            model_name='pengajuanta',
            name='judul',
        ),
        migrations.AddField(
            model_name='pengajuanta',
            name='bidang_minat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pengajuanta',
            name='catatan_admin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pengajuanta',
            name='ipk',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='pengajuanta',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pengajuanta',
            name='persetujuan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pengajuanta',
            name='semester',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pengajuanta',
            name='sks_lulus',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pengajuanta',
            name='tanggal_diperbarui',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
